services:
  server:
    depends_on:
      - database
    build:
      context: . 
    ports:
      - 8501:8501
    user: root
    env_file:
      -  custom.env
    volumes:
      - ./data/staging:/app/data/staging
    environment:
      - PIPE_DATA_PATH=./data/reglamentacion/
      - PIPE_COLLECTION_NAME=openai-750-overlap
      - PIPE_DB_ENDPOINT=http://qdrant:6333
      - PIPE_EMBEDDING_MODEL=text-embedding-ada-002
      - OPENAI_API_KEY=xxxx
  database:
    image: qdrant/qdrant:latest
    restart: always
    container_name: qdrant
    ports:
      - 6333:6333
      - 6334:6334
    expose:
      - 6333
      - 6334
    volumes:
      - ./qdrant_data:/qdrant/storage


